# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('user_ID', models.CharField(max_length=11, unique=True, verbose_name='手机')),
                ('user_sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('borm_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('hometown', models.CharField(blank=True, max_length=20, null=True, verbose_name='故乡')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('integral', models.IntegerField(default=0, verbose_name='积分')),
                ('coupons', models.SmallIntegerField(default=0, verbose_name='优惠券')),
                ('collection', models.IntegerField(default=0, verbose_name='收藏')),
                ('head_portrait', models.CharField(max_length=255, verbose_name='头像')),
                ('pay_password', models.CharField(blank=True, max_length=64, null=True, verbose_name='支付密码')),
            ],
            options={
                'verbose_name': '用户管理',
                'db_table': 'Members',
            },
        ),
    ]
