# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='members',
            name='collection',
            field=models.IntegerField(default=0, null=True, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='members',
            name='coupons',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='优惠券'),
        ),
        migrations.AlterField(
            model_name='members',
            name='head_portrait',
            field=models.CharField(max_length=255, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='members',
            name='integral',
            field=models.IntegerField(default=0, null=True, verbose_name='积分'),
        ),
    ]
