# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181120_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='members',
            name='head_portrait',
            field=models.ImageField(null=True, upload_to='head/logo', verbose_name='头像'),
        ),
    ]
