# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_addreses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addreses',
            old_name='district',
            new_name='harea',
        ),
        migrations.RenameField(
            model_name='addreses',
            old_name='province',
            new_name='hcity',
        ),
        migrations.RenameField(
            model_name='addreses',
            old_name='city',
            new_name='hproper',
        ),
    ]
