# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181128_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreses',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认地址'),
        ),
    ]
