# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('carriage_name', models.CharField(max_length=20, verbose_name='名称')),
                ('carriage_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
            ],
            options={
                'verbose_name': '运输方式',
                'verbose_name_plural': '运输方式',
            },
        ),
    ]
