# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20181125_1055'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('goods_count', models.SmallIntegerField(verbose_name='商品数量')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('order_number', models.CharField(max_length=64, verbose_name='订单编号')),
                ('order_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('userID', models.CharField(max_length=30, verbose_name='用户ID')),
                ('address_name', models.CharField(max_length=30, verbose_name='收货人姓名')),
                ('address_tel', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('address_site', models.CharField(max_length=150, verbose_name='订单地址')),
                ('order_state', models.BooleanField(choices=[(0, '待付款'), (1, '退发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], verbose_name='订单状态')),
                ('actually_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('address_note', models.CharField(max_length=255, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('payment_name', models.CharField(max_length=20, verbose_name='名称')),
                ('payment_img', models.ImageField(upload_to='order')),
            ],
            options={
                'verbose_name': '付款方式',
                'verbose_name_plural': '付款方式',
            },
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PaymentMethod', verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ModeTransport', verbose_name='运输方式'),
        ),
        migrations.AddField(
            model_name='ordercommodity',
            name='oderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus', verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='ordercommodity',
            name='skuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_SKU', verbose_name='商品sku_ID'),
        ),
    ]
