# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('trade_naem', models.CharField(max_length=50, verbose_name='专区名称')),
                ('trade_ID', models.CharField(max_length=20, verbose_name='商品ID')),
                ('describe', models.CharField(max_length=255, null=True, verbose_name='商品描述')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_shelves', models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '专区分类表',
                'verbose_name_plural': '专区分类表',
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Features_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '专区商品列表',
                'verbose_name_plural': '专区商品列表',
                'db_table': 'Features_list',
            },
        ),
        migrations.CreateModel(
            name='Goods_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('class_name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('introduction', models.CharField(max_length=255, null=True, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'goods_class',
            },
        ),
        migrations.CreateModel(
            name='Goods_SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('goods_abstract', models.CharField(max_length=250, null=True, verbose_name='商品简介')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('repertory', models.IntegerField(verbose_name='库存')),
                ('sales', models.SmallIntegerField(verbose_name='销量')),
                ('goods_LOGO', models.ImageField(upload_to='goods/%Y%m', verbose_name='logo地址')),
                ('is_shelves', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否上架')),
                ('goods_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_class', verbose_name='商品分类ID')),
            ],
            options={
                'verbose_name': '商品SKU表',
                'verbose_name_plural': '商品SKU表',
            },
        ),
        migrations.CreateModel(
            name='Goods_SPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('trade_naem', models.CharField(max_length=50, verbose_name='名称')),
                ('trade_ID', models.TextField(max_length=255, null=True, verbose_name='详情')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
            },
        ),
        migrations.CreateModel(
            name='Photo_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('img_url', models.ImageField(upload_to='goods/%Y%m/%d', verbose_name='图片地址')),
                ('trade_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_SKU', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '商品相册',
                'verbose_name_plural': '商品相册',
            },
        ),
        migrations.CreateModel(
            name='Shuffling_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('trade_naem', models.CharField(max_length=50, verbose_name='商品名称')),
                ('img_url_add', models.ImageField(null=True, upload_to='goods/%Y%m/%d', verbose_name='图片地址')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_carousel', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否轮播')),
                ('is_activity', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否活动')),
                ('url_activity', models.CharField(max_length=250, null=True, verbose_name='活动地址')),
                ('trade_ID', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_SKU', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '活动轮播表',
                'verbose_name_plural': '活动轮播表',
                'db_table': 'Shuffling_activity',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('update_data', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('unit_name', models.CharField(max_length=10, verbose_name='单位')),
                ('note', models.CharField(max_length=20, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品单位',
                'verbose_name_plural': '产品单位',
            },
        ),
        migrations.AddField(
            model_name='goods_sku',
            name='goods_spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_SPU', verbose_name='商品SPU_id'),
        ),
        migrations.AddField(
            model_name='features_list',
            name='trade_ID',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_SKU', verbose_name='商品SKU_ID'),
        ),
        migrations.AddField(
            model_name='features_list',
            name='zone_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Features', verbose_name='专区分类ID'),
        ),
    ]
