# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 09:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181124_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_spu',
            name='trade_ID',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='shuffling_activity',
            name='url_activity',
            field=models.CharField(default='null', max_length=250, null=True, verbose_name='活动地址'),
        ),
    ]
