# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181125_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods_sku',
            old_name='goods_spu_id',
            new_name='goods_spu',
        ),
    ]
