# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181125_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_sku',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_SPU', verbose_name='商品SPU_id'),
        ),
    ]
